### ISSUE TITLE
Meteor forums package

### ISSUE THREAD

**Issue by Morganjackson** [nolandg/meteor-crater-bunny#1]
Hey Noland, is this the package you mentioned on the Meteor forums?

https://forums.meteor.com/t/page-ranking-and-meteor-apps/19952/7

**Comment by nolandg** [comment]
Yep. Very unpolished right now though because I'm in Cuba for a while and internet is difficult. Feel free to use and PRs welcome. I'll write up a readme when I'm home.

**Comment by nolandg** [comment]
Readme is up now.
